services:
  - type: web
    name: pipeline-server
    env: node
    region: oregon
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
